#1 classwork
name = input('name: ')
last_name = input('last name: ')
age = input('age: ')
country = input('country: ')
city = input('city: ')
favourite_car = input('favourite car: ')
favourite_colour = input('favourite colour: ')
print("my name is " + name + ' ' + last_name + ', I live in ' + country + ' ' + city + ", my favourite car is " + favourite_car + ', and my favourite colour is ' + favourite_colour  + '.')

#2 classwork
num1 = int(input('num1 ='))
num2 = int(input('num2 ='))
num3 = int(input('num3 ='))
num4 = int(input('num4 ='))
num5 = int(input('num5 ='))
num6 = int(input('num6 ='))
num7 = int(input('num7 ='))
num8 = int(input('num8 ='))
num9 = int(input('num9 ='))
num10 = int(input('num10 ='))

print(num1 + num2)
print(num3 + num4)
print(num5 + num6)
print(num7 + num8)
print(num10 + num9)

print(num1 * num2)
print(num3 * num4)
print(num5 * num6)
print(num8 * num7)
print(num9 * num10)

print(num1 - num2)
print(num3 - num4)
print(num5 - num6)
print(num8 - num7)
print(num9 - num10)

print(num1 // num2)
print(num3 // num4)
print(num5 // num6)
print(num8 // num7)
print(num9 // num10)