print('Dialogue 1 "How to start learnig in GOA"')
print('Hello')
print('How are you')
print('I am fine.' + 'Thanks.' + ' ' + ' And you?')
print('Fine, thanks.')
print('May I ask you a question?')
print('Yes, of course!')
print('How old are you?')
print('I am' + ' ' + str(14) + ' ' + 'years old.')
print('Wow, I am 14 years old, too.')
print('Do you like programming?')
print('Yes, I am obsessed with programming.' + ' ' + 'I study it in GOA.')
print('Oh, I want to study programming, too.' + ' ' + 'Can you teach me how to get in that academy?')
print('Yes, at first you have to call to the director, than he will tell you everything about GOA.' + ' ' + 'Then you will have to make ' + str(2) + ' ' + 'task, and you are done you are in GOA academy')
print('That seems easy, thanks.' + ' ' + 'I will do this when I will get home')
print('Bye, then')
print('Bye')
print('Dialogue' + ' ' + '2' + ' ' + '"Chad vs Virgin"')
print("Chad: 'Hi there!'")
print("Virgin: 'Hi.'")
print("Chad: 'Why are you so fat?'")
print("'That's not your business!'" + " " + "says Virgin with envy.")
print("Chad: 'Where do you work, how much your wage?'")
print("Virgin: 'I don't work, I usualy play games and enjoy life, my parents pay everything for me." + " " + "How about you Mr do you enjoy life by working all day and night?'")
print("Chad: 'Yes I do, unlike you I work in Apple and my wage is" + ' ' + str(200000) + ' ' + "$ and I pay everything for myself and my parents.'")
print("Virgin: 'Do you go to gym? you have a great build.'")
print("Chad: 'Yes, I do. but I can't say same avout you.'")
print("Virgin: 'I dont't go to gym. Do you have your own home to?'")
print("Chad: 'Yes, I have 100000$ mansion.'")
print("Virgin: 'Wow, you know I want to become Chad too.'")
print("Chad: 'That's great. I'll help you. Start with going to gym.'")
print("Virgin: 'I feel stronger!'")
print("Chad: 'Now eat healthier.'")
print("Virgin: 'Now I am slimer!'")
print("Chad: 'Now start studying and find a job.'")
print("Virgin: 'Now I feel smarter, and I am rich!'")
print("Chad(1): 'Now you are chad too, congrats!'")
print("Chad(2): 'I am chad now, hooray! 🤫🧔🏻‍♂️'")
print("THE END")
print('I did not know what to print 40 times so I wrote dialogues.')