#1 classwork
name = input('name: ')
last_name = input('last name: ')
age = input('age: ')
country = input('country: ')
city = input('city: ')
favourite_car = input('favourite car: ')
favourite_colour = input('favourite colour: ')
print("my name is " + name + ' ' + last_name + ', I live in ' + country + ' ' + city + ", my favourite car is " + favourite_car + ', and my favourite colour is ' + favourite_colour  + '.')

#2 classwork
num1 = int(input('num1 ='))
num2 = int(input('num2 ='))
num3 = int(input('num3 ='))
num4 = int(input('num4 ='))
num5 = int(input('num5 ='))
num6 = int(input('num6 ='))
num7 = int(input('num7 ='))
num8 = int(input('num8 ='))
num9 = int(input('num9 ='))
num10 = int(input('num10 ='))
num11 = int(input('num11 ='))
num12 = int(input('num12 ='))
num13 = int(input('num13 ='))
num14 = int(input('num14 ='))
num15 = int(input('num15 ='))
num16 = int(input('num16 ='))
num17 = int(input('num17 ='))
num18 = int(input('num18 ='))
num19 = int(input('num19 ='))
num20 = int(input('num20 ='))

print(num1 + num2)
print(num3 + num4)
print(num5 + num6)
print(num7 + num8)
print(num10 + num9)
print(num11 + num12)
print(num13 + num14)
print(num15 + num16)
print(num17 + num18)
print(num19 + num20)

print(num1 * num2)
print(num3 * num4)
print(num5 * num6)
print(num8 * num7)
print(num9 * num10)
print(num11 * num12)
print(num13 * num14)
print(num15 * num16)
print(num17 * num18)
print(num19 * num20)

print(num1 - num2)
print(num3 - num4)
print(num5 - num6)
print(num8 - num7)
print(num9 - num10)
print(num11 - num12)
print(num13 - num14)
print(num15 - num16)
print(num17 - num18)
print(num19 - num20)

print(num1 // num2)
print(num3 // num4)
print(num5 // num6)
print(num8 // num7)
print(num9 // num10)
print(num11 // num12)
print(num13 // num14)
print(num15 // num16)
print(num17 // num18)
print(num19 // num20)

# int() - სტრინგს გარდაქმნის ინტეჯერად
# str() - ინტეჯერს გარდაქმნის სტრინგად
# type() - ტერმინალზე გამოაქვს ცვლადის ტიპი
# input() - მომხმარებელს აძლევს საშუალებას თავად შეიტანოს ცვლადის მნიშვნელობა.